title: TYZ Fashion
description: Youth-driven fashion redefined.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

nav:
  - title: Home
    url: /
  - title: Products
    url: /products/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

show_downloads: false
